name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: ['10.0', 10.x, '12.0', 12.x, '14.0', 14.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.1.0

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # Run for all environments
      - name: Run Tap Tests
        run: npm test

      # Push coverage for specific environment
      - name: Run Tap Tests (push coverage results)
        if: matrix.os == 'utuntu-latest' && matrix.node-version == '14.x'
        run: npm test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
